# Generated by Django 3.0.5 on 2025-01-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0030_auto_20221118_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='strain',
        ),
        migrations.AddField(
            model_name='sample',
            name='strain',
            field=models.ManyToManyField(related_name='samples', to='registry.Strain'),
        ),
    ]
