# Generated by Django 3.0.5 on 2025-03-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0031_auto_20250129_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
